// ---------------------------------------------------------------------------
// Wishly wedding registry catalog. Everything is something a couple needs for
// the wedding or married life, grouped into shelves. Photos come from
// cdn.dummyjson.com (free, stable). "Buy" points at an affiliate-tagged
// amazon.in search unless a product has an explicit `buyUrl`.
//
// The site owner can ALSO add gifts from the admin panel (/admin) which are
// stored in the database and merged into these shelves for everyone.
// ---------------------------------------------------------------------------

import type { CatalogProduct } from "./types";

export const CATEGORIES: { id: string; label: string; blurb: string }[] = [
  { id: "beauty", label: "Beauty & Glow", blurb: "For the bride's radiant day" },
  { id: "bride-outfits", label: "For the Bride", blurb: "Outfits to shine in" },
  { id: "her-footwear", label: "Her Shoes & Bags", blurb: "The finishing touches" },
  { id: "jewellery", label: "Jewellery & Accessories", blurb: "Heirlooms in the making" },
  { id: "groom", label: "For the Groom", blurb: "Sharp for the sherwani & after" },
  { id: "his", label: "His Watches & Scents", blurb: "Timeless picks for him" },
  { id: "home", label: "Home & Furniture", blurb: "The big pieces for a new home" },
  { id: "kitchen", label: "Kitchen & Dining", blurb: "For the first meals as a family" },
  { id: "cookware", label: "Cookware & Appliances", blurb: "Everything the kitchen needs" },
  { id: "tech", label: "Tech & Gadgets", blurb: "For the modern couple" },
  { id: "audio", label: "Audio & Entertainment", blurb: "Music for the new home" },
  { id: "fitness", label: "Fitness & Leisure", blurb: "Stay active together" },
  { id: "honeymoon", label: "Honeymoon & Travel", blurb: "For the journey ahead" },
];

// Invitation templates. `deep` drives the guest-page ribbon, names and accents;
// `hero` is the background photo on the couple's shared invitation page.
export const TEMPLATES: {
  id: string;
  label: string;
  deep: string;
  bg: string;
  tile: string;
  hero: string;
}[] = [
  { id: "royal", label: "Royal Maroon", deep: "#7c1d2b", bg: "#fbf1ea", tile: "#f2e3d2", hero: "/wedding/couple-gold.jpg" },
  { id: "marigold", label: "Marigold", deep: "#b3721b", bg: "#fdf3e0", tile: "#f6e6c8", hero: "/wedding/pheras.jpg" },
  { id: "rose", label: "Rose Petals", deep: "#b64760", bg: "#fceef1", tile: "#f6dbe1", hero: "/wedding/hero-petals.jpg" },
  { id: "classic", label: "Classic Ivory", deep: "#8a7a53", bg: "#f8f5ee", tile: "#ece5d5", hero: "/wedding/silhouette.jpg" },
  { id: "mehndi", label: "Mehndi Green", deep: "#5f7a4b", bg: "#f2f5ea", tile: "#e4ecd4", hero: "/wedding/agni.jpg" },
];

const CDN = "https://cdn.dummyjson.com/product-images";

function p(id: string, name: string, imagePath: string, category: string, amazonQuery?: string): CatalogProduct {
  return {
    id,
    name,
    image: `${CDN}/${imagePath}/thumbnail.webp`,
    category,
    amazonQuery: amazonQuery ?? name,
  };
}

export const PRODUCTS: CatalogProduct[] = [
  p("c1", "Essence Mascara Lash Princess", "beauty/essence-mascara-lash-princess", "beauty", "Essence Mascara Lash Princess"),
  p("c2", "Eyeshadow Palette with Mirror", "beauty/eyeshadow-palette-with-mirror", "beauty", "Eyeshadow Palette with Mirror"),
  p("c3", "Powder Canister", "beauty/powder-canister", "beauty", "Powder Canister"),
  p("c4", "Red Lipstick", "beauty/red-lipstick", "beauty", "Red Lipstick"),
  p("c5", "Red Nail Polish", "beauty/red-nail-polish", "beauty", "Red Nail Polish"),
  p("c6", "Attitude Super Leaves Hand Soap", "skin-care/attitude-super-leaves-hand-soap", "beauty", "Attitude Super Leaves Hand Soap"),
  p("c7", "Olay Ultra Moisture Shea Butter Body Wash", "skin-care/olay-ultra-moisture-shea-butter-body-wash", "beauty", "Olay Ultra Moisture Shea Butter Body Wash"),
  p("c8", "Vaseline Men Body and Face Lotion", "skin-care/vaseline-men-body-and-face-lotion", "beauty", "Vaseline Men Body and Face Lotion"),
  p("c9", "Calvin Klein CK One", "fragrances/calvin-klein-ck-one", "beauty", "Calvin Klein CK One"),
  p("c10", "Chanel Coco Noir Eau De", "fragrances/chanel-coco-noir-eau-de", "beauty", "Chanel Coco Noir Eau De"),
  p("c11", "Black Women’s Gown", "womens-dresses/black-women's-gown", "bride-outfits", "Black Women's Gown"),
  p("c12", "Corset Leather With Skirt", "womens-dresses/corset-leather-with-skirt", "bride-outfits", "Corset Leather With Skirt"),
  p("c13", "Corset With Black Skirt", "womens-dresses/corset-with-black-skirt", "bride-outfits", "Corset With Black Skirt"),
  p("c14", "Dress Pea", "womens-dresses/dress-pea", "bride-outfits", "Dress Pea"),
  p("c15", "Marni Red & Black Suit", "womens-dresses/marni-red-&-black-suit", "bride-outfits", "Marni Red & Black Suit"),
  p("c16", "Blue Frock", "tops/blue-frock", "bride-outfits", "Blue Frock"),
  p("c17", "Girl Summer Dress", "tops/girl-summer-dress", "bride-outfits", "Girl Summer Dress"),
  p("c18", "Gray Dress", "tops/gray-dress", "bride-outfits", "Gray Dress"),
  p("c19", "Short Frock", "tops/short-frock", "bride-outfits", "Short Frock"),
  p("c20", "Tartan Dress", "tops/tartan-dress", "bride-outfits", "Tartan Dress"),
  p("c21", "Black & Brown Slipper", "womens-shoes/black-&-brown-slipper", "her-footwear", "Black & Brown Slipper"),
  p("c22", "Calvin Klein Heel Shoes", "womens-shoes/calvin-klein-heel-shoes", "her-footwear", "Calvin Klein Heel Shoes"),
  p("c23", "Golden Shoes Woman", "womens-shoes/golden-shoes-woman", "her-footwear", "Golden Shoes Woman"),
  p("c24", "Pampi Shoes", "womens-shoes/pampi-shoes", "her-footwear", "Pampi Shoes"),
  p("c25", "Red Shoes", "womens-shoes/red-shoes", "her-footwear", "Red Shoes"),
  p("c26", "Blue Women’s Handbag", "womens-bags/blue-women's-handbag", "her-footwear", "Blue Women's Handbag"),
  p("c27", "Heshe Women’s Leather Bag", "womens-bags/heshe-women's-leather-bag", "her-footwear", "Heshe Women's Leather Bag"),
  p("c28", "Prada Women Bag", "womens-bags/prada-women-bag", "her-footwear", "Prada Women Bag"),
  p("c29", "White Faux Leather Backpack", "womens-bags/white-faux-leather-backpack", "her-footwear", "White Faux Leather Backpack"),
  p("c30", "Women Handbag Black", "womens-bags/women-handbag-black", "her-footwear", "Women Handbag Black"),
  p("c31", "Green Crystal Earring", "womens-jewellery/green-crystal-earring", "jewellery", "Green Crystal Earring"),
  p("c32", "Green Oval Earring", "womens-jewellery/green-oval-earring", "jewellery", "Green Oval Earring"),
  p("c33", "Tropical Earring", "womens-jewellery/tropical-earring", "jewellery", "Tropical Earring"),
  p("c34", "Silver Steel Watch", "womens-watches/iwc-ingenieur-automatic-steel", "jewellery", "IWC Ingenieur Automatic Steel"),
  p("c35", "Moonphase Dress Watch", "womens-watches/rolex-cellini-moonphase", "jewellery", "Cellini Moonphase"),
  p("c36", "Two-tone Ladies’ Watch", "womens-watches/rolex-datejust-women", "jewellery", "Datejust Women"),
  p("c37", "Watch Gold for Women", "womens-watches/watch-gold-for-women", "jewellery", "Watch Gold for Women"),
  p("c38", "Women’s Wrist Watch", "womens-watches/women's-wrist-watch", "jewellery", "Women's Wrist Watch"),
  p("c39", "Black Sun Glasses", "sunglasses/black-sun-glasses", "jewellery", "Black Sun Glasses"),
  p("c40", "Classic Sun Glasses", "sunglasses/classic-sun-glasses", "jewellery", "Classic Sun Glasses"),
  p("c41", "Green and Black Glasses", "sunglasses/green-and-black-glasses", "jewellery", "Green and Black Glasses"),
  p("c42", "Blue & Black Check Shirt", "mens-shirts/blue-&-black-check-shirt", "groom", "Blue & Black Check Shirt"),
  p("c43", "Gigabyte Aorus Men Tshirt", "mens-shirts/gigabyte-aorus-men-tshirt", "groom", "Gigabyte Aorus Men Tshirt"),
  p("c44", "Man Plaid Shirt", "mens-shirts/man-plaid-shirt", "groom", "Man Plaid Shirt"),
  p("c45", "Man Short Sleeve Shirt", "mens-shirts/man-short-sleeve-shirt", "groom", "Man Short Sleeve Shirt"),
  p("c46", "Men Check Shirt", "mens-shirts/men-check-shirt", "groom", "Men Check Shirt"),
  p("c47", "Nike Air Jordan 1 Red And Black", "mens-shoes/nike-air-jordan-1-red-and-black", "groom", "Nike Air Jordan 1 Red And Black"),
  p("c48", "Nike Baseball Cleats", "mens-shoes/nike-baseball-cleats", "groom", "Nike Baseball Cleats"),
  p("c49", "Puma Future Rider Trainers", "mens-shoes/puma-future-rider-trainers", "groom", "Puma Future Rider Trainers"),
  p("c50", "Sports Sneakers Off White & Red", "mens-shoes/sports-sneakers-off-white-&-red", "groom", "Sports Sneakers Off White & Red"),
  p("c51", "Sports Sneakers Off White Red", "mens-shoes/sports-sneakers-off-white-red", "groom", "Sports Sneakers Off White Red"),
  p("c52", "Brown Leather Belt Watch", "mens-watches/brown-leather-belt-watch", "his", "Brown Leather Belt Watch"),
  p("c53", "Classic Dress Watch", "mens-watches/longines-master-collection", "his", "Longines Master Collection"),
  p("c54", "Black Dial Leather Watch", "mens-watches/rolex-cellini-date-black-dial", "his", "Cellini Date Black Dial"),
  p("c55", "Moonphase Dress Watch", "mens-watches/rolex-cellini-moonphase", "his", "Cellini Moonphase"),
  p("c56", "Steel Link Watch", "mens-watches/rolex-datejust", "his", "Datejust"),
  p("c57", "Rolex Submariner Watch", "mens-watches/rolex-submariner-watch", "his", "Submariner Watch"),
  p("c58", "Dior J’adore", "fragrances/dior-j'adore", "his", "Dior J'adore"),
  p("c59", "Dolce Shine Eau de", "fragrances/dolce-shine-eau-de", "his", "Dolce Shine Eau de"),
  p("c60", "Gucci Bloom Eau de", "fragrances/gucci-bloom-eau-de", "his", "Gucci Bloom Eau de"),
  p("c61", "Upholstered Bed", "furniture/annibale-colombo-bed", "home", "Annibale Colombo Bed"),
  p("c62", "3-Seater Sofa", "furniture/annibale-colombo-sofa", "home", "Annibale Colombo Sofa"),
  p("c63", "Wooden Bedside Table", "furniture/bedside-table-african-cherry", "home", "Bedside Table African Cherry"),
  p("c64", "Accent Armchair", "furniture/knoll-saarinen-executive-conference-chair", "home", "Knoll Saarinen Executive Conference Chair"),
  p("c65", "Vanity with Mirror", "furniture/wooden-bathroom-sink-with-mirror", "home", "Wooden Bathroom Sink With Mirror"),
  p("c66", "Decoration Swing", "home-decoration/decoration-swing", "home", "Decoration Swing"),
  p("c67", "Family Tree Photo Frame", "home-decoration/family-tree-photo-frame", "home", "Family Tree Photo Frame"),
  p("c68", "House Showpiece Plant", "home-decoration/house-showpiece-plant", "home", "House Showpiece Plant"),
  p("c69", "Plant Pot", "home-decoration/plant-pot", "home", "Plant Pot"),
  p("c70", "Table Lamp", "home-decoration/table-lamp", "home", "Table Lamp"),
  p("c71", "Bamboo Spatula", "kitchen-accessories/bamboo-spatula", "kitchen", "Bamboo Spatula"),
  p("c72", "Black Aluminium Cup", "kitchen-accessories/black-aluminium-cup", "kitchen", "Black Aluminium Cup"),
  p("c73", "Black Whisk", "kitchen-accessories/black-whisk", "kitchen", "Black Whisk"),
  p("c74", "Boxed Blender", "kitchen-accessories/boxed-blender", "kitchen", "Boxed Blender"),
  p("c75", "Carbon Steel Wok", "kitchen-accessories/carbon-steel-wok", "kitchen", "Carbon Steel Wok"),
  p("c76", "Chopping Board", "kitchen-accessories/chopping-board", "kitchen", "Chopping Board"),
  p("c77", "Citrus Squeezer Yellow", "kitchen-accessories/citrus-squeezer-yellow", "kitchen", "Citrus Squeezer Yellow"),
  p("c78", "Egg Slicer", "kitchen-accessories/egg-slicer", "kitchen", "Egg Slicer"),
  p("c79", "Electric Stove", "kitchen-accessories/electric-stove", "kitchen", "Electric Stove"),
  p("c80", "Fine Mesh Strainer", "kitchen-accessories/fine-mesh-strainer", "kitchen", "Fine Mesh Strainer"),
  p("c81", "Fork", "kitchen-accessories/fork", "kitchen", "Fork"),
  p("c82", "Glass", "kitchen-accessories/glass", "kitchen", "Glass"),
  p("c83", "Grater Black", "kitchen-accessories/grater-black", "cookware", "Grater Black"),
  p("c84", "Hand Blender", "kitchen-accessories/hand-blender", "cookware", "Hand Blender"),
  p("c85", "Ice Cube Tray", "kitchen-accessories/ice-cube-tray", "cookware", "Ice Cube Tray"),
  p("c86", "Kitchen Sieve", "kitchen-accessories/kitchen-sieve", "cookware", "Kitchen Sieve"),
  p("c87", "Knife", "kitchen-accessories/knife", "cookware", "Knife"),
  p("c88", "Lunch Box", "kitchen-accessories/lunch-box", "cookware", "Lunch Box"),
  p("c89", "Microwave Oven", "kitchen-accessories/microwave-oven", "cookware", "Microwave Oven"),
  p("c90", "Mug Tree Stand", "kitchen-accessories/mug-tree-stand", "cookware", "Mug Tree Stand"),
  p("c91", "Pan", "kitchen-accessories/pan", "cookware", "Pan"),
  p("c92", "Plate", "kitchen-accessories/plate", "cookware", "Plate"),
  p("c93", "Red Tongs", "kitchen-accessories/red-tongs", "cookware", "Red Tongs"),
  p("c94", "Silver Pot With Glass Cap", "kitchen-accessories/silver-pot-with-glass-cap", "cookware", "Silver Pot With Glass Cap"),
  p("c95", "iPhone 5s", "smartphones/iphone-5s", "tech", "iPhone 5s"),
  p("c96", "iPhone 6", "smartphones/iphone-6", "tech", "iPhone 6"),
  p("c97", "iPhone 13 Pro", "smartphones/iphone-13-pro", "tech", "iPhone 13 Pro"),
  p("c98", "iPhone X", "smartphones/iphone-x", "tech", "iPhone X"),
  p("c99", "Oppo A57", "smartphones/oppo-a57", "tech", "Oppo A57"),
  p("c100", "Oppo F19 Pro Plus", "smartphones/oppo-f19-pro-plus", "tech", "Oppo F19 Pro Plus"),
  p("c101", "Oppo K1", "smartphones/oppo-k1", "tech", "Oppo K1"),
  p("c102", "MacBook Pro 14 Inch Space Grey", "laptops/apple-macbook-pro-14-inch-space-grey", "tech", "MacBook Pro 14 Inch Space Grey"),
  p("c103", "Asus Zenbook Pro Dual Screen Laptop", "laptops/asus-zenbook-pro-dual-screen-laptop", "tech", "Asus Zenbook Pro Dual Screen Laptop"),
  p("c104", "Huawei Matebook X Pro", "laptops/huawei-matebook-x-pro", "tech", "Huawei Matebook X Pro"),
  p("c105", "Lenovo Yoga 920", "laptops/lenovo-yoga-920", "tech", "Lenovo Yoga 920"),
  p("c106", "New DELL XPS 13 9300 Laptop", "laptops/new-dell-xps-13-9300-laptop", "tech", "New DELL XPS 13 9300 Laptop"),
  p("c107", "Amazon Echo Plus", "mobile-accessories/amazon-echo-plus", "audio", "Amazon Echo Plus"),
  p("c108", "Airpods", "mobile-accessories/apple-airpods", "audio", "Airpods"),
  p("c109", "AirPods Max Silver", "mobile-accessories/apple-airpods-max-silver", "audio", "AirPods Max Silver"),
  p("c110", "Airpower Wireless Charger", "mobile-accessories/apple-airpower-wireless-charger", "audio", "Airpower Wireless Charger"),
  p("c111", "HomePod Mini Cosmic Grey", "mobile-accessories/apple-homepod-mini-cosmic-grey", "audio", "HomePod Mini Cosmic Grey"),
  p("c112", "iPhone Charger", "mobile-accessories/apple-iphone-charger", "audio", "iPhone Charger"),
  p("c113", "MagSafe Battery Pack", "mobile-accessories/apple-magsafe-battery-pack", "audio", "MagSafe Battery Pack"),
  p("c114", "Watch Series 4 Gold", "mobile-accessories/apple-watch-series-4-gold", "audio", "Watch Series 4 Gold"),
  p("c115", "Beats Flex Wireless Earphones", "mobile-accessories/beats-flex-wireless-earphones", "audio", "Beats Flex Wireless Earphones"),
  p("c116", "iPhone 12 Silicone Case with MagSafe Plum", "mobile-accessories/iphone-12-silicone-case-with-magsafe-plum", "audio", "iPhone 12 Silicone Case with MagSafe Plum"),
  p("c117", "Monopod", "mobile-accessories/monopod", "audio", "Monopod"),
  p("c118", "Selfie Lamp with iPhone", "mobile-accessories/selfie-lamp-with-iphone", "audio", "Selfie Lamp with iPhone"),
  p("c119", "American Football", "sports-accessories/american-football", "fitness", "American Football"),
  p("c120", "Baseball Ball", "sports-accessories/baseball-ball", "fitness", "Baseball Ball"),
  p("c121", "Baseball Glove", "sports-accessories/baseball-glove", "fitness", "Baseball Glove"),
  p("c122", "Basketball", "sports-accessories/basketball", "fitness", "Basketball"),
  p("c123", "Basketball Rim", "sports-accessories/basketball-rim", "fitness", "Basketball Rim"),
  p("c124", "Cricket Ball", "sports-accessories/cricket-ball", "fitness", "Cricket Ball"),
  p("c125", "Cricket Bat", "sports-accessories/cricket-bat", "fitness", "Cricket Bat"),
  p("c126", "Cricket Helmet", "sports-accessories/cricket-helmet", "fitness", "Cricket Helmet"),
  p("c127", "Cricket Wicket", "sports-accessories/cricket-wicket", "fitness", "Cricket Wicket"),
  p("c128", "Feather Shuttlecock", "sports-accessories/feather-shuttlecock", "fitness", "Feather Shuttlecock"),
  p("c129", "Football", "sports-accessories/football", "fitness", "Football"),
  p("c130", "Golf Ball", "sports-accessories/golf-ball", "fitness", "Golf Ball"),
  p("c131", "Realme C35", "smartphones/realme-c35", "honeymoon", "Realme C35"),
  p("c132", "Realme X", "smartphones/realme-x", "honeymoon", "Realme X"),
  p("c133", "Realme XT", "smartphones/realme-xt", "honeymoon", "Realme XT"),
  p("c134", "Galaxy S7", "smartphones/samsung-galaxy-s7", "honeymoon", "S7"),
  p("c135", "Galaxy S8", "smartphones/samsung-galaxy-s8", "honeymoon", "S8"),
  p("c136", "Galaxy S10", "smartphones/samsung-galaxy-s10", "honeymoon", "S10"),
  p("c137", "iPad Mini 2021 Starlight", "tablets/ipad-mini-2021-starlight", "honeymoon", "iPad Mini 2021 Starlight"),
  p("c138", "Galaxy Tab S8 Plus Grey", "tablets/samsung-galaxy-tab-s8-plus-grey", "honeymoon", "Tab S8 Plus Grey"),
  p("c139", "Galaxy Tab White", "tablets/samsung-galaxy-tab-white", "honeymoon", "Tab White"),
];
